version: '3'
services:
  toybox-www:
    container_name: toybox-www
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROJECT: ${PROJECT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - './.aws:/root/.aws'
      - '.:/${PROJECT}'
      - '/${PROJECT}/src/node_modules'
    environment: 
      - NODE_ENV=development
      - AWS_PROFILE=inves-global
    entrypoint: top
